#!/usr/bin/env bash

# Needed for Sourcetree to find binaries
export PATH=/usr/local/bin:$PATH

status_before=$(git status -vv)

pretty-quick --staged

status_after=$(git status -vv)

if [ "$status_before" != "$status_after" ]; then
    echo -e "\nReformatted project, check the changed files and recommit."
    exit 1
else
    exit 0
fi
