FROM node:14.7.0-alpine3.12

RUN adduser --disabled-password user
WORKDIR /home/user/app
RUN chown user:user /home/user/app

USER user

COPY --chown=user:user package.json .
COPY --chown=user:user yarn.lock .
RUN yarn install

COPY --chown=user:user . .
RUN yarn build

CMD ["yarn", "start"]
