version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
