FROM node:14.10.1-alpine3.12

RUN adduser --disabled-password user
WORKDIR /home/user/app
RUN chown user:user /home/user/app

USER user

COPY --chown=user:user package.json .
COPY --chown=user:user yarn.lock .
RUN yarn install

COPY --chown=user:user . .

ARG API_URL

RUN yarn build

CMD ["yarn", "start"]
