version: 2

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - checkout
      - run:
          name: "Build frontend"
          command:  docker build -t frontend . 
      - run:
          name: "Run type-check and linting"
          command: >
            docker run --rm --volume=$(pwd):/app frontend sh -c
            "yarn type-check && yarn lint"
