version: 2

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Run linters, type-check, and build"
          command: docker build --target circleci --tag frontend . && docker run frontend
