version: 2

orbs:
  cypress: cypress-io/cypress@1.26.0

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: 'Check commits of the PR branch'
          command: ./.circleci/check_commits.sh
      - run:
          name: 'Run linters, type-check, and build'
          command: docker build --target circleci --tag frontend . && docker run frontend

workflows:
  build:
    jobs:
      - cypress/run:
          start: yarn dev
          wait-on: 'http://localhost:3001'
          no-workspace: true
          post-steps:
            - store_artifacts:
                path: coverage
