version: 2

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Run linter and type-check"
          command: docker build -t frontend-circleci . && docker run frontend-circleci
