version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    # parallelism: 2 # TODO: Enable parallelism on Apr 1, 2021
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.13  # https://github.com/yarnpkg/yarn/issues/8389#issuecomment-754099816
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
      - run:
          name: "Run linters, type-check, build and Cypress"
          command: >
            docker build --target circleci --tag frontend --build-arg CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM --build-arg CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY .
            && docker run --name frontend frontend
            && docker cp frontend:/home/user/app/coverage/clover.xml .
      - codecov/upload:
          file: clover.xml
