export const urls = {
    activity: '/account/activity',
    changePassword: '/account/change-password',
    deleteAccount: '/account/delete-account',
    editProfile: '/account/edit-profile',
    resetPassword: '/account/reset-password',
    starred: '/account/starred',
    verifyAccount: '/account/verify-account',
    course: '/courses/[id]',
    resource: '/resources/[id]',
    school: '/schools/[id]',
    user: '/users/[id]',
    about: '/about',
    contact: '/contact',
    createCourse: '/create-course',
    faq: '/faq',
    getStarted: '/get-started',
    home: '/',
    login: '/login',
    logout: '/logout',
    confirmLogout: '/logout/confirm',
    privacy: '/privacy',
    register: '/register',
    search: '/search',
    terms: '/terms',
    uploadResource: '/upload-resource',
};

export const apiUrls = {
    removeCookie: '/api/remove-cookie',
    setCookie: '/api/set-cookie',
};
