export const urls = {
  activity: '/account/activity',
  changePassword: '/account/change-password',
  deleteAccount: '/account/delete-account',
  myData: '/account/my-data',
  editProfile: '/account/edit-profile',
  resetPassword: '/account/reset-password',
  starred: '/account/starred',
  verifyAccount: '/account/verify-account',
  course: (id: string): string => `/courses/${id}`,
  resource: (id: string): string => `/resources/${id}`,
  school: (id: string): string => `/schools/${id}`,
  user: (id: string): string => `/users/${id}`,
  contact: '/contact',
  forTeachers: '/for-teachers',
  addCourse: '/add-course',
  index: '/',
  guidelines: '/guidelines',
  home: '/home',
  login: '/login',
  logout: '/logout',
  privacy: '/privacy',
  register: '/register',
  score: '/score',
  search: '/search',
  terms: '/terms',
  uploadResource: '/upload-resource',
  values: '/values',
};
