export const urls = {
  course: (slug: string): string => `/courses/${slug}`,
  resource: (slug: string): string => `/resources/${slug}`,
  school: (slug: string): string => `/schools/${slug}`,
  user: (slug: string): string => `/users/${slug}`,
  about: '/about',
  accountSettings: '/account-settings',
  activity: '/activity',
  addCourse: '/add-course',
  badges: '/badges',
  changePassword: '/change-password',
  contact: '/contact',
  deleteAccount: '/delete-account',
  editProfile: '/edit-profile',
  guidelines: '/guidelines',
  home: '/home',
  index: '/',
  login: '/login',
  logout: '/logout',
  myData: '/my-data',
  privacy: '/privacy',
  register: '/register',
  resetPassword: '/reset-password',
  score: '/score',
  search: '/search',
  starred: '/starred',
  terms: '/terms',
  uploadMaterial: '/upload-material',
  values: '/values',
  verifyAccount: '/verify-account',
};
